; Asp gacha — Adafruit Feather ESP32 + stepper (PUL/DIR/ENA) + MQTT WSS
; CLI: pio run | pio run -t upload | pio device monitor

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
monitor_echo = yes
monitor_eol = CRLF
monitor_filters = send_on_enter, time, colorize
monitor_rts = 0
monitor_dtr = 0
upload_speed = 921600

lib_deps =
	waspinator/AccelStepper@^1.64
	bblanchon/ArduinoJson@^7.0.4

build_flags =
	-D CORE_DEBUG_LEVEL=0
	-D CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=1
	-Wno-deprecated-declarations
